# Generated by Django 5.1.3 on 2024-11-24 23:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('analyticId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=80)),
                ('evaporationRate', models.FloatField(null=True)),
                ('trend', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytic Data',
                'verbose_name_plural': 'Analytic Data Records',
                'db_table': 'Analytic_data',
                'ordering': ['region', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Iotdata',
            fields=[
                ('dataId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('temperatureWater', models.CharField(max_length=80)),
                ('temperatureAir', models.CharField(max_length=80)),
                ('humidity', models.CharField(max_length=80)),
                ('windSpeed', models.CharField(max_length=80)),
                ('precipitation', models.CharField(max_length=80)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IoT Data',
                'verbose_name_plural': 'IoT Data Records',
                'db_table': 'IoT_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('price', models.FloatField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product_data',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('profileId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('role', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User_data',
                'ordering': ['firstname', 'lastname'],
            },
        ),
    ]
