# === PostgreSQL Database Configuration ===
spring.datasource.url=jdbc:postgresql://dpg-d0a08i1r0fns73dv1flg-a.oregon-postgres.render.com/students_6pm1
spring.datasource.username=students_6pm1_user
spring.datasource.password=XwWfW59MiUN7RYUcHlSXaqZus38MYV7m

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver


# === Application Metadata ===
spring.application.name=management
server.port=8080
